language: go
matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on
  - go: 1.16.x

go_import_path: github.com/n3k0fi5t/travisci_demo

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./; fi

script:
  - go test -v